# Generated by Django 3.1.5 on 2021-01-26 12:39

from django.db import migrations, models
import main_gusto.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0002_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(upload_to=main_gusto.models.Dish.get_file_name_dishes),
        ),
    ]
