# Generated by Django 3.1.5 on 2021-01-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0004_auto_20210126_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingridients',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='weight',
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
