# Generated by Django 3.1.5 on 2021-02-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0009_banners_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
